### ISSUE TITLE
reloading data

### ISSUE THREAD

**Issue by kristian-puccio** [aksonov/react-native-tableview#10]
I'm using the render2 from the examples method of drawing a table with a mix of inline static cells (for testing) and a bunch rendered into a variable and included in sections using { varWithItems }

I'm having trouble updating the cells.

Basically I'm waiting for an api call then updating the variable. What is happening is that when I scroll the cells out of the view then their contents get updated.

But the total number of cells isn't updated.

I'm guessing we need to reloadData on the table view but I'm not sure where that should go

**Comment by aksonov** [comment]
Please give me example repo to see the problem.

**Comment by kristian-puccio** [comment]
Here you go, this.props.events is an immutable list that starts as empty list and gets populated with an api call.

```
     render() {

		const items = this.props.events.map( e => {
			return (<Item value="1" detail="Detail1" >{e.get('Name')}</Item>);
		});

        return (
            <View style={styles.container}>

				<TableView
					style={styles.table}
					tableViewStyle={TableView.Consts.Style.Plain}
					tableViewCellStyle={TableView.Consts.CellStyle.Subtitle}
					onPress={(event) => console.log(event)}>

					<Section label="Section 1" arrow={true}>
						{items}
						<Item value="1" detail="Detail1" >Item 1</Item>
						<Item value="1" detail="Detail1" >Item 1</Item>
						<Item value="1" detail="Detail1" >Item 1</Item>
					</Section>

				</TableView>


				<LoadingIndicator isShown={this.props.isFetching} />
            </View>
        );

```

**Comment by aksonov** [comment]
Please make working github repo, so i could run the project.

**Comment by kristian-puccio** [comment]
I think I worked out what the problem is the {items} is an array, so when
the loop inside _stateFromProps happens it's not picking it up as a valid
'type' either a section or cell so it's just missed.

**Comment by aksonov** [comment]
I'm not sure that i've understood, but if there any problem, give me link to working demo or you may close this issue.
