### ISSUE TITLE
Please help me fix this: undefined is not an object (evaluating 'React.PropTypes.func')

### ISSUE THREAD

**Issue by mrnav90** [aksonov/react-native-tableview#100]
I already follow step by step install document library and when run on app, this happen with me.
Can you please help fix this. Thanks!
@aksonov 
Follow image:
![simulator screen shot may 25 2016 2 17 33 pm](https://cloud.githubusercontent.com/assets/9253581/15531287/cb6ec22a-2283-11e6-8130-209a318bd321.png)

**Comment by frontvu** [comment]
+1

**Comment by frontvu** [comment]
Can you confirm that this now works?

**Comment by mrnav90** [comment]
@frontvu: Thanks you.
@aksonov: Thanks you merged

**Comment by frontvu** [comment]
Ok. Please close this issue

**Comment by leecmm** [comment]
This problem still exists

**Comment by frontvu** [comment]
Are you using latest version?

**Comment by leecmm** [comment]
yes
<img width="344" alt="6649206e-94b8-44f1-a963-b7871bba7c05" src="https://cloud.githubusercontent.com/assets/5915703/15596996/927aa1ce-23fe-11e6-9466-c6510153fb6c.png">
<img width="375" alt="4995bc6a-2138-4a12-bb83-54647a17560d" src="https://cloud.githubusercontent.com/assets/5915703/15597003/a6a80664-23fe-11e6-8b04-a2d070aa1ab0.png">

**Comment by aksonov** [comment]
Sorry but error seems to be in your SettingsView/index, why you think that it is this component?
