### ISSUE TITLE
Horizontal borders disappear on smaller devices (iPhone 4s & 5)

### ISSUE THREAD

**Issue by joegoodall1** [aksonov/react-native-tableview#107]
As the title implies the horizontal borders disappear between each cell on the iPhone 4s and 5.
Anyone else encountered this and resolved it? If so, what was the solution?

**Comment by mikemonteith** [comment]
It seems that the separatorStyle is getting set to null somewhere in the Objective-C side, but I don't know enough about Obj-C to fully understand what's going on.

I fixed my problem temporarily by setting `_tableView.separatorStyle = UITableViewCellSeparatorStyleSingleLine;` in RNTableView.m `(void)createTableView` function.
Obviously this isn't a long-term solution for this module but might give a hint as to what's causing the problem. It seems like `self.separatorStyle` is being deleted when other props update (?)

**Comment by Reptilijonas** [comment]
Separator setter is missing in RNTableView.

Simply adding this >>>

`- (void)setSeparatorStyle:(UITableViewCellSeparatorStyle)separatorStyle {
    _tableView.separatorStyle = separatorStyle;
}`

to RNTableView.m fixed the issue for me.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
