### ISSUE TITLE
Xcode warning: the behavior of the UICollectionViewFlowLayout is not defined

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-tableview#109]
When I pop up an Alert component from the onPress method of an `<Item>` or `<Cell>` I get the following warning in the Xcode console.

```
    the behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
 The relevant UICollectionViewFlowLayout instance is <_UIAlertControllerCollectionViewFlowLayout: 0x14914bd00>, and it is attached to <UICollectionView: 0x14882ee00; frame = (0 91.6667; 270 44); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x14914c910>; layer = <CALayer: 0x14914c2b0>; contentOffset: {0, 0}; contentSize: {0, 0}> collection view layout: <_UIAlertControllerCollectionViewFlowLayout: 0x14914bd00>.

Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

```

I asked about this on [StackOverflow](http://stackoverflow.com/questions/38317351/inscrutable-error-mesage-from-xcode-when-using-the-react-native-alert-api) but have not received a response. @aksonov, @nyura123, I wonder if it could be related to the implementation of `react-native-tableview`?

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
