### ISSUE TITLE
Separate states between sections

### ISSUE THREAD

**Issue by christopherdro** [aksonov/react-native-tableview#11]
Currently theres not way to differentiate selections between different sections. 
Am I missing something or is this the way it's suppose to currently work?

Also, I think we want to disable checkmarks if the sections `arrow` property is set to true.

Thoughts?

**Comment by aksonov** [comment]
Yes, it makes sense, i will do this soon. If you want to make it by yourself, PR is welcome.

**Comment by aksonov** [comment]
Fixed for 1.2.0 version
