### ISSUE TITLE
turn 'deselectRowAtIndexPath' on/off

### ISSUE THREAD

**Issue by DrBeak1** [aksonov/react-native-tableview#111]
I'm using the module for an ipad and want to keep the tapped cell selected until a new cell is tapped (standard ipad tableview behavior). I was able to achieve this by going into the RNTableView.m class and modifying the code, but making this settable from the table view instantiation would be best. If this option already exists and I just missed it please do let me know.

Thanks for the great mod.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
