### ISSUE TITLE
react-native deprecation warning: RNAppGlobals

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-tableview#114]
Running this component shows the following warning in xcode:

`RNAppGlobals is deprecated/no longer needed and will be removed soon`

**Comment by nyura123** [comment]
This warning should go away if you remove the RNAppGlobals lines from AppDelegate.m.
Those special lines are no longer needed for 'reactModuleForCell'.

**Comment by chetstone** [comment]
Ah, thanks..
