### ISSUE TITLE
Missing merge request fix for 1.52

### ISSUE THREAD

**Issue by codeNgamer** [aksonov/react-native-tableview#116]
I have version 1.52 of this module and it appears that #110  was merged. Can you confirm that the merge request was actually rolled into 1.52 because my copy doesn't appear to have it even after deleting the local files and re-installing. I copy and pasted the contents of "RNTableView/RNTableViewManager.m" from that merge request as a sanity check and i'm getting

```
No visible @interface for 'RNTableView' declares the selector 'initWithBridge:
```

**Comment by ilyaivjev** [comment]
+1

**Comment by t2n3qqq** [comment]
Same problems

**Comment by LaurenceRolandJames** [comment]
Same issue --> a temporary fix is to include the module in the package.json using the github link:

"react-native-tableview": "git+https://github.com/aksonov/react-native-tableview.git"

**Comment by iRoachie** [comment]
New version will be posted this week!
