### ISSUE TITLE
Bug when TextInput is added into the cell

### ISSUE THREAD

**Issue by jojonarte** [aksonov/react-native-tableview#117]
I've added a textinput in a cell within a Section here's a video of what happens.

http://www.screencast.com/t/vLl5tsMb1Rc

The the textInput loses focus when I'm adding a new list dynamically as search results come.

I've tried not putting the search component within the tableview and it works properly.
 I'm using this https://github.com/FaridSafi/react-native-google-places-autocomplete.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
