### ISSUE TITLE
Item accessory

### ISSUE THREAD

**Issue by iRoachie** [aksonov/react-native-tableview#121]
How do I add an accessory to an Item? It's not explained well in the readme

**Comment by mithunm93** [comment]
@iRoachie did you figure this out? or....

**Comment by mithunm93** [comment]
For future reference:
```
<TableView>
  <Section>
    <Item accessoryType={ TableView.Consts.AccessoryType.DisclosureButton }
      Some Text
    </Item>
  </Section>
</TableView>
```

**Comment by iRoachie** [comment]
@mithunm93 Thanks mate! Could not figure it out for the life of me. The documentation really needs a cleanup
