### ISSUE TITLE
Problem with load more data

### ISSUE THREAD

**Issue by roysG** [aksonov/react-native-tableview#123]
When i tried to load more data, the data is loaded but the scroll is jumping always to start.

How can i fix it?

**Comment by roysG** [comment]
any update? someone?

**Comment by monkeyxdd** [comment]
i miss the same problem,can you fix it?

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
