### ISSUE TITLE
undefined is not an object (evaluating _reactNative.NativeModules.UIManager.RNTableView.Constants

### ISSUE THREAD

**Issue by PaulRBerg** [aksonov/react-native-tableview#124]
Hello. I read #81, but I checked three times and I surely linked libRNTableView.a. I still receive this message:

undefined is not an object (evaluating _reactNative.NativeModules.UIManager.RNTableView.Constants)

Can you please help me?

**Comment by razvan-paul** [comment]
Apparently, the 'undefined' situations occurs only in the Release scheme. Now I switched to Debug and it happens just like in #120

**Comment by bronylexx** [comment]
Same issue here except it happens for me in both, Release and Debug schemes.

**Comment by intmainvoid** [comment]
Have you done step 4 in the readme?
```
4. In the XCode project navigator, select your project, select the Build Phases tab and in the Link Binary With Libraries section add libRNTableView.a
```
Not doing that step properly would cause this error

**Comment by iRoachie** [comment]
This problem's been since fixed and is in master. A new version should be published this week
