### ISSUE TITLE
Does this support swipe to delete to UITableViewCell?

### ISSUE THREAD

**Issue by coodoo** [aksonov/react-native-tableview#13]
Can't seem to found any mentioning of this in the doc or source, hence the question, thanks!

**Comment by aksonov** [comment]
It is not supported at this moment.

**Comment by aksonov** [comment]
Deleting/sorting should be done within latest version 1.3.0. onChange event in this case, so you could manage/persist your items on JS side.

**Comment by coodoo** [comment]
Woohoo! Thanks for making this happen :)

**Comment by aksonov** [comment]
Sorry, just realized that I've implemented edit mode, but it doesn't include swipe to delete option.

Pavel.

**Comment by aksonov** [comment]
allowsMultipleSelectionDuringEditing=NO did the trick, so feature is implemented within 1.3.2

**Comment by coodoo** [comment]
Great, thanks for the effort!
