### ISSUE TITLE
undefined is not an object (evaluating 'RNTableViewConsts.CellEditingStyle')

### ISSUE THREAD

**Issue by alexkuc** [aksonov/react-native-tableview#139]
I am receiving an error message for index.js (from the node module itself):
`undefined is not an object (evaluating 'RNTableViewConsts.CellEditingStyle')`

This part of the code is raising error:
```
getDefaultProps() {
        return {
            tableViewCellEditingStyle: RNTableViewConsts.CellEditingStyle.Delete,
            autoFocusAnimate: true,
            alwaysBounceVertical: true,
            scrollEnabled: true,
            sectionIndexTitlesEnabled: false,
            showsHorizontalScrollIndicator: true,
            showsVerticalScrollIndicator: true,
        };
    },
```

<img width="487" alt="screenshot 2017-08-11 02 16 24" src="https://user-images.githubusercontent.com/3331946/29185292-5c21966c-7e3b-11e7-934e-002b322374d6.png">

I have verified that I indeed linked the library. What further steps should I take to resolve (or troubleshoot) this error message?

**Comment by mikeromano38** [comment]
Same here after upgrading to react-native 0.47.2

**Comment by intmainvoid** [comment]
This will be fixed by this PR 143
