### ISSUE TITLE
Editing and Sorting Features

### ISSUE THREAD

**Issue by vlucas** [aksonov/react-native-tableview#14]
Editing, deleting, and sorting features are the main differentiation point between a TableView and ListView. These are the main things I am looking for when using a TableView.

You're off to a great start here (thank you for taking this on!), but in my view, the deleting and sorting behaviors are absolutely critical for a full, usable TableView implementation that most people are looking for - even before the performance issues are solved.

**Comment by aksonov** [comment]
Deleting/sorting should be done within latest version 1.3.0. I'm not sure what do you mean by editing.

**Comment by vlucas** [comment]
Awesome! I just meant putting the table in edit mode. :)
