### ISSUE TITLE
"undefined is not an object" error when running Example 1 from README.md

### ISSUE THREAD

**Issue by TomLisankie** [aksonov/react-native-tableview#147]
I am getting an error that states `undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RNTableView.Constants')` when running [Example 1 from the README.md](https://github.com/aksonov/react-native-tableview#examples). I am running React Native version 0.50.3.

![Error Message](https://i.imgur.com/ztIRX7y.png)

**Comment by iRoachie** [comment]
Hey! All the examples will be updated in the next release. You can follow the progress on the `update` branch, or [this](https://github.com/aksonov/react-native-tableview/pull/149) pr

**Comment by iRoachie** [comment]
Fixed and merged in master. Will be available in 2.0
