### ISSUE TITLE
No selected item initially 

### ISSUE THREAD

**Issue by iSimar** [aksonov/react-native-tableview#15]
I'm trying to get a tableview with selectable items but none of the items are to be selected initially. 

ex: 
````
<Section label="My Items" arrow={false}>
   <Item>Item 1</Item>
    <Item>Item 2</Item>
    <Item>Item 3</Item>
 </Section>
````

It only seems to be working when I have at least one of the items set to `selected={true}`

**Comment by aksonov** [comment]
You are right, selected={true} is intended usage, also you could set selectedValue=VALUE for TableView element where VALUE is 'value' of item which should be selected. I don't think that the component must select some element initially (first?) if no selected value is set - sometimes users don't want to see any selection.

**Comment by chirag04** [comment]
This seems like a valid bug to me. I agree sometimes the users don't want to see any selection, but what if want users to select without having any initially default selected value.

**Comment by chirag04** [comment]
Ok. so adding ``selectedValue=''`` makes it work.
