### ISSUE TITLE
App crash on p2r

### ISSUE THREAD

**Issue by markuplab** [aksonov/react-native-tableview#159]
**2.1.0**
App crash after pull2refresh. Nothing special, just follow repo guide. Custom cell design.

react: "16.3.1"
react-native": "0.55.3"

![image](https://user-images.githubusercontent.com/4974184/39230818-20d2cf50-4892-11e8-9836-9d0e66f70e9c.png)

**Comment by markuplab** [comment]
Sorry, private repo, i can't. But maybe i can prepare example.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
