### ISSUE TITLE
TableView Tag does not render anything

### ISSUE THREAD

**Issue by liamse** [aksonov/react-native-tableview#160]
I use 

- react-native version `0.55.2` 
- `xcode 9.2`

And use some other modules:

- react-native-navigation 1.1.446 (wix company developed).
- naitive-base 2.4.2

The result of <TableView> is nothing. In `react-devtools` it exist but the height is zero. I try to set  `flex:1` as written at Example1 but none of them is worked.

**Comment by nyura123** [comment]
@liamse do all the parent views have a height? try to make them flex or give a height somewhere.

**Comment by liamse** [comment]
Yes @nyura123, The answer of you question is yes.
I init a new react-native project only to test `<Example1 />` component. it does not show anything like before. I find out that I need to add `width` to style of `<TableView>` to it appear. 

If I find time, I am going to test it with `react-native-navigation` as well.

**Comment by liamse** [comment]
I found my question answer. First of all it does not related to `react-native-navigation`.
I init a react-native project and try to use react-native-tableview Example1 as I said before. But the `width` of tableview is set to zero. After a while, I figure out the `alignItems: 'center'` in above View makes this problem. I create [TableViewTutorial Repository](https://github.com/liamse/TableViewTutorial) and explain it by detail.
