### ISSUE TITLE
Scroll To Index Support

### ISSUE THREAD

**Issue by hammadzz** [aksonov/react-native-tableview#163]
Does this library allow scrolling to item at a certain index? I can't seem to find it in the source.

**Comment by iRoachie** [comment]
Hey @hammadzz it's not implemented currently. There's the scrollTo which scrolls in pixels.

You'll need to make a ref to use it.
```jsx
<TableView
   ref={ref => this.tableView = ref}
 >
```

Then:
```js
this.tableView.scrollTo(x, y, animated?)
```

**Comment by itome** [comment]
I created PR (https://github.com/aksonov/react-native-tableview/pull/164) to support scrollToIndex feature.
You can try this version by changing `package.json` file as following.
```
"react-native-tableview": "^2.1.1",
↓
"react-native-tableview": "git://github.com/itome/react-native-tableview.git",
```

At the moment, this worked only for my code.
So feel free to ask me or fix my implementation.

**Comment by iRoachie** [comment]
Added in 2.2.0 https://github.com/aksonov/react-native-tableview#scrolltoindex
