### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.NativeModules.RNTableViewManager.Constants')

### ISSUE THREAD

**Issue by gao520sun** [aksonov/react-native-tableview#178]
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.4 => 0.50.4

**Comment by damon8to24** [comment]
I had the same problem. How did you solve it? @gao520sun

**Comment by mtford90** [comment]
@damon8to24 and anybody else who comes across this, I solved this using platform specific code i.e. `Component.ios.js` and `Component.android.js`
