### ISSUE TITLE
Can't use Item and Cell components side by side

### ISSUE THREAD

**Issue by Purii** [aksonov/react-native-tableview#18]
Great component! Hope that you could help me, with the following use case.

**Issue:** Using Item and Cell components side by side results in a misbehavior of the whole tableview:

![simulator screen shot 06 10 2015 22 39 28](https://cloud.githubusercontent.com/assets/7056989/10321849/357f0694-6c7b-11e5-968a-d1221de019e9.png)
```
<TableView
 style={{flex:1}}
 tableViewStyle={TableView.Consts.Style.Grouped}
 tableViewCellStyle={TableView.Consts.CellStyle.Subtitle}
 >
    <Section label="Section 1" arrow={true}>
        <Cell><Text>Heyja!</Text></Cell>
        <Item>Über</Item>
    </Section>
    <Section label="Section 2">
        <Item style={TableView.Consts.CellStyle.Subtitle} onPress={this.handleResetFavorites}>
            Option
        </Item>
    </Section>
</TableView>
```

**Use case:** I want to build the following screen, which seems to have two pitfalls:

1. Use an ActivityIndicatorIOS inside a row
2. View + TableView with single scrollbar. This seems not possible, since the tableview-component scrolls on it's own and the view-component stays fixed.

*How could I realize this?*

![simulator screen shot 06 10 2015 22 44 00](https://cloud.githubusercontent.com/assets/7056989/10321988/ee7ccf0a-6c7b-11e5-988b-8148d0176556.png)

**Comment by aksonov** [comment]
You cannot mix Cell and Item elements. Check demo with custom cells.
