### ISSUE TITLE
reactModuleForCell is not a property of TableView

### ISSUE THREAD

**Issue by freerangenerd** [aksonov/react-native-tableview#183]
The instructions for Editable Complex Components says to pass your cell component as a prop for TableView:

<TableView reactModuleForCell="TableViewExampleCell" >

https://github.com/aksonov/react-native-tableview#editable-complex-components

TableView does not have a reactModuleForCell prop in TableViewProps.

Is this no longer supported? Is the documentation wrong?

**Comment by iRoachie** [comment]
Just added it to the props in [v2.3.1](https://github.com/aksonov/react-native-tableview/releases/tag/2.3.1). Thanks for bringing up.
