### ISSUE TITLE
Are cellSeparatorInset and cellLayoutMargins required props?

### ISSUE THREAD

**Issue by henrikra** [aksonov/react-native-tableview#189]
I just started using this library and TS compiler yells at me about these two props. If I don't have them the table renders fine. But they are marked as required. Is this just mistake in TypeScipt types?

![image](https://user-images.githubusercontent.com/12229968/48121364-664e5880-e27d-11e8-9a63-a65ec2aff70d.png)
![image](https://user-images.githubusercontent.com/12229968/48121392-79612880-e27d-11e8-9f24-b2b1a987d855.png)

**Comment by iRoachie** [comment]
Sorry about that they should be optional.

**Comment by henrikra** [comment]
If you make PR I can review it :)
