### ISSUE TITLE
How to scroll to the bottom of the list?

### ISSUE THREAD

**Issue by henrikra** [aksonov/react-native-tableview#191]
Hello

I am developing chat application and I am experimenting if this component fits my needs. So far so good. One thing that I don't see in the api and what I would like to use is that I would like to use method like `scrollToBottom` that would do the same as other scroll methods but it would scroll to the bottom of the list :). Do you guys have any tips for that for this library?  Because for example `Flatlist` has this method but I had other problems with that library (which I dont have with react-native-tableview :))

**Comment by henrikra** [comment]
Hmm okay looks like this is working nicely 👍 

`this.newTable.current.scrollToIndex({ index: this.state.myArray.length - 1 });`

**Comment by iRoachie** [comment]
Nice! Great that you posted what you found here so others can find it

**Comment by henrikra** [comment]
No worries 😃  Btw now I found actual bug with `Cell` component. Can you check it out here and give your opinion? https://github.com/aksonov/react-native-tableview/issues/192
