### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.NativeModules.RNTableViewManager.Constants')

### ISSUE THREAD

**Issue by davesherratt** [aksonov/react-native-tableview#194]
Version 2.4.1

undefined is not an object (evaluating '_reactNative.NativeModules.RNTableViewManager.Constants')

- [ ]

**Comment by iRoachie** [comment]
Hey please make sure the library is linked correctly, and then you re-run the app with `react-native run-ios`.

Also you can double check if it's linked correctly by following the Manual Instructions section in the Readme.

**Comment by myriky** [comment]
same here :(
also i'm using with Expo

**Comment by iRoachie** [comment]
@myriky This library doesn't support expo, it's a native library.

**Comment by MobileDev418** [comment]
I have a same problem.
I am integrating this on android project.
'react-native run-android`

**Comment by MobileDev418** [comment]
@iRoachie is not support on android?

**Comment by iRoachie** [comment]
Not as yet. There's an open PR for it

**Comment by raymondkpwong** [comment]
@iRoachie Which PR is related to this?

**Comment by iRoachie** [comment]
My bad, wrong repo 🤦🏽‍♂️

**Comment by Dimasprog** [comment]
> Version 2.4.1
> 
> undefined is not an object (evaluating '_reactNative.NativeModules.RNTableViewManager.Constants')
> 
> * [ ]

[davesherratt](https://github.com/davesherratt), did u find solution?
