### ISSUE TITLE
Question: why does RN not using UITableView from the start?

### ISSUE THREAD

**Issue by oferRounds** [aksonov/react-native-tableview#195]
Just wondering what is the reason for that, same question for UICollectionView. I think I’ve read something that the new architecture that they are now working on on Facebook, will allow this, but I’m not sure why/how

Anyhow, thanks for this awesome library!

**Comment by iRoachie** [comment]
I’m not sure! They maybe would’ve wanted more customization from the JS side

**Comment by oferRounds** [comment]
yes.. Still curious to know if there a was another/different reason, following the comment I mentioned above

**Comment by iRoachie** [comment]
You could try asking on the react-native repo

**Comment by oferRounds** [comment]
thanks @iRoachie, I'll try!
