### ISSUE TITLE
Remove "git+" in the repository url from package.json

### ISSUE THREAD

**Issue by n-kumari** [aksonov/react-native-tableview#198]
Is there a reason to prepend the repository url with `git+` in [package.json](https://github.com/aksonov/react-native-tableview/blob/master/package.json#L12)? 

Reading https://docs.npmjs.com/files/package.json#urls-as-dependencies, looks like the master branch is going to be used anyway since the commit-ish is not specified. (The commit-ish can be any tag, sha, or branch which is supplied as an argument to git checkout.)

I believe since the library is defaulting to master branch, the `git+` can be removed from the repository url.

**Comment by iRoachie** [comment]
This is generated automatically by `npm init`.

**Comment by n-kumari** [comment]
I see. We use cocoapods as the dependency manager and it breaks when trying to fetch the url prepended with `git+`.

`git+` syntax  is not supported by cocoapods (Source: Podspec Syntax Reference
https://guides.cocoapods.org/syntax/podspec.html#source.) 

As `git+` is not adding any value in this case of package.json(since it defaults to master anyway), removing `git+` should be good. This would help other users who use cocoapods as their dependency manager to not run in the issue. 

If I opened a PR to remove `git+`, would it be accepted?

**Comment by iRoachie** [comment]
Just merged in
