### ISSUE TITLE
[request] add selection callback to each table cell 

### ISSUE THREAD

**Issue by plrthink** [aksonov/react-native-tableview#20]
Add selection callback to each table cell will be great.

**Comment by aksonov** [comment]
It is already done, have you tried onPress handler?
      
      return (
            <TableView style={{flex:1}}>
                <Section label={this.state.sectionLabel}  arrow={true}>
                    <Item onPress={Actions.example1}>Example with custom cells</Item>
                    <Item onPress={Actions.example2}>Example with app bundle JSON data</Item>
                    <Item onPress={Actions.example3}>Example with multiple sections</Item>
                    <Item onPress={Actions.edit}>Example with editing mode</Item>
                </Section>
            </TableView>

**Comment by plrthink** [comment]
Oh, sorry for not checking before creating this issue.
