### ISSUE TITLE
Build error on RN 0.60.4: No visible @interface for 'RCTEventDispatcher' declares the selector 'sendInputEventWithName

### ISSUE THREAD

**Issue by emielvanliere** [aksonov/react-native-tableview#207]
Building with React Native 0.60.4 gives me the following error in `RNTableViewManager.m` on line 256:

"No visible @interface for 'RCTEventDispatcher' declares the selector 'sendInputEventWithName:body:"

**Comment by iRoachie** [comment]
There's a PR open to fix this. #203

**Comment by iRoachie** [comment]
Fixed in v3.0.0. https://github.com/aksonov/react-native-tableview/releases/tag/3.0.0
