### ISSUE TITLE
Support for Custom Accessory Views

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#28]
See [`accessoryView`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewCell_Class/index.html#//apple_ref/occ/instm/UITableViewCell/accessoryView) and [broadly](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewCell_Class/index.html#//apple_ref/occ/instm/UITableViewCell/accessoryView).

**Comment by aksonov** [comment]
It seems duplicate of #21
