### ISSUE TITLE
Does it has the same property of ListView?

### ISSUE THREAD

**Issue by haledeng** [aksonov/react-native-tableview#3]
Does it has the same property of ListView, like dataSource, renderRow and so on.

**Comment by aksonov** [comment]
No. It is more similar to PickerIOS now, please check examples. I will add propTypes for all elements soon.

Pavel.

**Comment by haledeng** [comment]
I think, It should be more common. Users can define row by themselves.

**Comment by aksonov** [comment]
Sure, you can do it like it is done for PickerIOS, using map() function inside TableView. Also you could programmatically create and pass 'sections' array (list of tableview sections).

But if you are talking definition of cell UI, not data, it seems much more complex. I'm thinking how it is possible to achieve - get custom JS views from native iOS code and set it as table cell. Any ideas are welcome!

**Comment by aksonov** [comment]
Check #5 . Latest 1.1.0 version has custom Cell elements, it is not the same as ListView syntax, but you could easily create it. Maybe i will add the renderRow function, or you could create patch.
