### ISSUE TITLE
Change TableView background color?

### ISSUE THREAD

**Issue by nicholasalanbrown** [aksonov/react-native-tableview#32]
Great package. Is there any way to change the gray background color of the overall TableView?

**Comment by aksonov** [comment]
I've added transparent background for native UITableView for 1.4.3 version, so now you could set any background you want in RN styles.

**Comment by chetstone** [comment]
I can't seem to get this to work. 
`<TableView style={{backgroundColor: 'green'}}>`
does nothing -- the element is still white. What am I missing?
I also tried tintColor but get an error message when used as part of the style and it doesn't do anything when used on its own as a prop.

**Comment by roysG** [comment]
any updates?

**Comment by iRoachie** [comment]
Setting style on the TableView will only changer the color of the background so the `Item` itself will still be white. Right now the only workaround is to create a custom cell.
