### ISSUE TITLE
autoFocus={false} does not work

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#34]
I am setting `autoFocus={false}` on a TableView but it still seems to scroll down to the selected item.

**Comment by cancan101** [comment]
Could this be an issue?: https://github.com/aksonov/react-native-tableview/blob/8a2376afbcbfd2b8e66dc2413496b4eda027113a/RNTableView/RNTableView.m#L63

**Comment by aksonov** [comment]
The problem was that property is not listed in RNTableViewManager, fixed in 1.4.3, please check
