### ISSUE TITLE
Expose allowsMultipleSelection

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#36]
Currently `allowsMultipleSelection` is not exposed. `allowsMultipleSelectionDuringEditing` _is_ exposed.

**Comment by aksonov** [comment]
Could you clarify? PR is welcome.

**Comment by cancan101** [comment]
>A Boolean value that determines whether users can select more than one row outside of editing mode.

>This property controls whether multiple rows can be selected simultaneously outside of editing mode. When the value of this property is YES, each row that is tapped acquires a selected appearance. Tapping the row again removes the selected appearance. If you access indexPathsForSelectedRows, you can get the index paths that identify the selected rows.

I believe that [this code](https://github.com/aksonov/react-native-tableview/blob/710554a3c44e2f058c1ce87e22ddbc35bb2b0155/RNTableView/RNTableView.m#L263-L284) also needs to be updated to handle multiple selections.
