### ISSUE TITLE
Managing the Reordering of Rows

### ISSUE THREAD

**Issue by adamkrell** [aksonov/react-native-tableview#4]
Thank you for putting the work into this component!

Can the component be put into "editing" mode so the cells can be [reordered](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TableView_iPhone/ManageReorderRow/ManageReorderRow.html)? Or, is this a planned feature?

Again, thank you for working on this. It will be so useful.

**Comment by aksonov** [comment]
Sorry, it is not planned because it is not clear how to transfer data back to JS after reordering. Usage of events for each reordering/deleting  looks quite complex. Anyway PR is welcome!

**Comment by adamkrell** [comment]
If I get a chance, I'll see if I can work on this. I'd like to have this feature and you've done a great deal of the foundational work, so if I can break away from my current project I'll see what I can do. Thanks.

**Comment by aksonov** [comment]
Should be done for latest version 1.3.0

**Comment by adamkrell** [comment]
Awesome!
