### ISSUE TITLE
Possible to Create Row / Cell without Section

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#42]
Is there some way to create a Row / Cell without a section? (or at the very least have the ability to hide the section header).

**Comment by cancan101** [comment]
This might just work if the section label is set to `''`.

**Comment by mosesoak** [comment]
+1 on this request

**Comment by njt1982** [comment]
@cancan101 Leaving label as empty seems to cause it to be hidden

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
