### ISSUE TITLE
selectedValue Should be Renamed to defaultSelectedValue

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#44]
Either `selectedValue` should be renamed to `defaultSelectedValue` or it should be made into a controlled value. 

Right now, `selectedValue` is not a controlled value. i.e. updating that prop should control the value selected in the component whereas right now it is just used as the initial value.

For a similar prop, see [`textinput`](https://facebook.github.io/react-native/docs/textinput.html#props) which has both `value` and `defaultValue`.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
