### ISSUE TITLE
Moving rows only inside their sections

### ISSUE THREAD

**Issue by gpbl** [aksonov/react-native-tableview#45]
Rows can be moved _between_ sections, while I'd like to constrain rows inside their own section. Is there  a way to do that?

**Comment by aksonov** [comment]
You may submit PR to do it:

1. Introduce new property, like moveWithinSectionOnly
2.  Add method to RNTableView and if moveWithinSectionOnly is true, reject proposedDestinationIndexPath (i.e. return sourceIndexPath) if section is different

- (NSIndexPath *)tableView:(UITableView *)tableView
        targetIndexPathForMoveFromRowAtIndexPath:(NSIndexPath *)sourceIndexPath
        toProposedIndexPath:(NSIndexPath *)proposedDestinationIndexPath {

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/TableView_iPhone/ManageReorderRow/ManageReorderRow.html

**Comment by gpbl** [comment]
OK, try to see if #47 does it: however I have no idea how can I test it. Could you help me on that?

**Comment by aksonov** [comment]
Check my comments there. What do you mean you can't test it? Just run your code with your modified RNTableView component inside node_modules with several sections and move from one section to another?

**Comment by aksonov** [comment]
Or you meant unit tests? If so, it is really difficult,  i didn't found the way.

**Comment by gpbl** [comment]
I fork the project, I open RNTableView.xcodeproj and edit the code. 
However I receive there many errors I can't even use autocomplete (I'm on XCode 7.1). 

So, to test if the changes are working, I should copy/paste the changed files inside `node_modules`. I was looking for a better way... :-)
