### ISSUE TITLE
Ability to hide a Cell?

### ISSUE THREAD

**Issue by studio-dude** [aksonov/react-native-tableview#46]
Since the number of Cells cannot change across calls to render (https://github.com/aksonov/react-native-tableview/issues/19), is it possible to hide a Cell? I tried various css (height=0, display: none, etc) but I cannot seem to accomplish it.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
