### ISSUE TITLE
Plan to support contentView?

### ISSUE THREAD

**Issue by ecesena** [aksonov/react-native-tableview#5]
Hi, nice job! Do you plan to support contentView?
My use case is to have in each cell some text left-aligned and other right-aligned.

**Comment by aksonov** [comment]
Please check latest version 1.1.0, should be done there. Use <TableView.Cell> element under <TableView.Section> to define custom UI cell.

**Comment by aksonov** [comment]
example 4 is added to show custom cell usage.

**Comment by ecesena** [comment]
It looks great! I'll check it asap.
