### ISSUE TITLE
Expose keyboardDismissMode prop

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#55]
Expose [`keyboardDismissMode`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScrollView_Class/#//apple_ref/occ/instp/UIScrollView/keyboardDismissMode) prop on TableView.

[RN's scroll view exposes](https://facebook.github.io/react-native/docs/scrollview.html#keyboarddismissmode).

**Comment by rjoonas** [comment]
:+1: Much needed.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
