### ISSUE TITLE
Add Pull to Refresh

### ISSUE THREAD

**Issue by cancan101** [aksonov/react-native-tableview#59]
This can be done using the [`refreshControl` on the `UITableViewController`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewController_Class/index.html#//apple_ref/occ/instp/UITableViewController/refreshControl). For more info see [for example](http://www.appcoda.com/pull-to-refresh-uitableview-empty/).

**Comment by Xosmond** [comment]
This is really important to use with tableview

**Comment by iRoachie** [comment]
I’ll see if I can add it this weekend.

**Comment by iRoachie** [comment]
Will commit tomorrow.

![pull-to-refresh](https://user-images.githubusercontent.com/5962998/35315053-aff877b4-00a0-11e8-8fd6-79d71d61fd8d.gif)

**Comment by iRoachie** [comment]
https://github.com/aksonov/react-native-tableview/pull/155

**Comment by Xosmond** [comment]
Great!!

**Comment by iRoachie** [comment]
Released in [2.1.0](https://github.com/aksonov/react-native-tableview/releases/tag/2.1.0). Can check the readme or example app on how to use. https://github.com/aksonov/react-native-tableview#pull-to-refresh. 💯
