### ISSUE TITLE
More control over Cell?

### ISSUE THREAD

**Issue by theaqua** [aksonov/react-native-tableview#62]
Does Cell have more than plain text control? For example, icons, labels, even switcher, just like Settings in iOS.

![img_0642](https://cloud.githubusercontent.com/assets/775692/11769678/01594056-a1fe-11e5-86f6-c86858427987.jpg)

**Comment by theaqua** [comment]
Or input, for example.

**Comment by aksonov** [comment]
It would be nice extension, PR is welcome.

**Comment by theaqua** [comment]
IDK how 🤒

**Comment by nickw** [comment]
@theaqua see: https://github.com/aksonov/react-native-tableview/issues/21 - this can be accomplished with a `<Cell>` component and some custom styling
