### ISSUE TITLE
Contributors wanted!

### ISSUE THREAD

**Issue by aksonov** [aksonov/react-native-tableview#65]
Developers! I'm glad that this component is so popular and thanks for great feedback about it, i did my best to fix issues to make it component more robust, however i don't have currently much time to work on suggested enhancements. If anyone is willing to help, let me know, I will add you as collaborator to the project.

**Comment by nyura123** [comment]
Hi, I've worked on an enhancement that allows rendering into iOS cells by using react root views. Each cell becomes a mini react 'app', and cellForRowAtIndexPath re-uses them and asks react to re-render with the right data. 
Let me know if you'd be interested in taking a look/having this integrated.

**Comment by aksonov** [comment]
@nyura123 Looks interesting!

**Comment by nyura123** [comment]
@aksonov yeah, it seems to work pretty well! I can put it on a branch (never contributed to an open-source project before so I'm not really sure what the steps are :)

**Comment by aksonov** [comment]
Could you check my component sources and see what could be done to integrate?

**Comment by nyura123** [comment]
I've integrated it already on my branch (into RNTableView/Manager.m and the demo app index.ios.js), I just can't push the branch right now.

**Comment by nyura123** [comment]
for now, I forked & checked in the code there: https://github.com/nyura123/react-native-tableview

**Comment by aksonov** [comment]
@nyura123 do you want to become collaborator of this component?

**Comment by nyura123** [comment]
@aksonov, sure, that'd be great - thanks!
