### ISSUE TITLE
[Question] Is there a way to disable a cell?

### ISSUE THREAD

**Issue by ivanbrens** [aksonov/react-native-tableview#66]
I've found that I can place a **<View />** right in the cell and customize it anyway I see fit, but its still clickable and prevents clicking the content

![](https://zippy.gfycat.com/PreciousGoldenGemsbok.gif)

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
