### ISSUE TITLE
Horizontal separate row borders

### ISSUE THREAD

**Issue by yarax** [aksonov/react-native-tableview#69]
At some point I noticed, that grey borders between rows disappeared. So I created a new project from scratch, using basic example 

```
'use strict';

var React = require('react-native');
var { AppRegistry } = React;
var TableView = require('react-native-tableview');
var Section = TableView.Section;
var Item = TableView.Item;

class AwesomeProject extends React.Component {
    render(){
        return (
            <TableView style={{flex:1}}
                       allowsToggle={true}
                       allowsMultipleSelection={true}
                       tableViewStyle={TableView.Consts.Style.Grouped}
                       tableViewCellStyle={TableView.Consts.CellStyle.Subtitle}
                       onPress={(event) => console.log(event)}>
                <Section label="Section 1" arrow={true}>
                    <Item value="1" detail="Detail1" >Item 1</Item>
                    <Item value="2">Item 2</Item>
                </Section>
                <Section label="Section 2" arrow={false}>
                    <Item selected={true}>Item 1</Item>
                    <Item>Item 2</Item>
                    <Item>Item 3</Item>
                </Section>
            </TableView>
        );
    }
}

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

But table is without borders: ![](https://i.gyazo.com/6575b38dc88c86aab0825a14cb9ba7f9.png)

react-native-tableview version is 1.4.3

**Comment by yarax** [comment]
Also I can't do it manually, because according to this thread https://github.com/facebook/react-native/issues/29 react-native doesn't support one-side borders, except of View component.

**Comment by yarax** [comment]
Now I see, that it depends on tableViewCellStyle, sorry, maybe it will be useful for someone else

**Comment by joegoodall1** [comment]
Any solution to this? Having the same problem that horizontal borders disappear on smaller devices eg. iPhone 5.

**Comment by joegoodall1** [comment]
Hi @yarax ,

How did you resolve this problem.

You mentioned tableViewCellStyle. What did you set that as?

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
