### ISSUE TITLE
Ability to style section headers

### ISSUE THREAD

**Issue by rmdort** [aksonov/react-native-tableview#7]
Feature request

**Comment by aksonov** [comment]
Sorry, out of time currently, you welcome to do PR for this.

**Comment by aksonov** [comment]
Atleast do detailed FR for this - what exactly should be styled and how. Closing it for now.

**Comment by rmdort** [comment]
Noted. I was thinking if the following is doable?

````
<TableView sectionHeaderStyle = {{padding: 10}}>
</TableView>
````

**Comment by aksonov** [comment]
Sorry, it seems not to be possible - i can’t pass JS styles to native UITableView.
