### ISSUE TITLE
Native JSON Support

### ISSUE THREAD

**Issue by julio-rivera** [aksonov/react-native-tableview#70]
How would one generate the TableView with a JSON generated from Javascript? It says its supported but it would be helpful if there was some sort of example in the README

**Comment by yarax** [comment]
+1 came across with the same issue, that's mentioned in docs, but there is no description how to use it. So finally I decided to use something like this
```
    render(){
        var body = store.getState().categories.map(function (item) {
            return <Cell value="" style={styles.cell}>
             <Text style={styles.text}>{item.name}</Text>
             <Cell style={styles.label}><Text style={styles.inner}>{item.count}</Text></Cell>
             </Cell>
        });

        return (
            <TableView>
                <Section>
                    {body}
                </Section>
            </TableView>
        );
    }
```

**Comment by VonD** [comment]
Hi,

You first have to add the json file to your iOS application bundle (right click on your project's name and select Add files to...).
Then you can pass the file name to the component's `json` prop.

If your file is named countries.json : 

```es6
<TableView json="countries" />
```

The json structure should be like so : 

```json
[
  {"items": [
      {"label": "label1", "value": "value1"},
      {"label": "label2", "value": "value2"}
  ]}
]
```

You can check examples 2 and 3 on the Readme, or the examples folder.
