### ISSUE TITLE
TableView inside NavigatorIOS content insets

### ISSUE THREAD

**Issue by ifunk** [aksonov/react-native-tableview#75]
When using TableView inside a NavigatorIOS component, the TableView is obscured by the Navigator header. 

I tried wrapping the TableView inside a ScrollView (which should position content correctly below the header). However, the TableView doesn't display at all in that case. I set { flex: 1 } for both ScrollView and TableView.

Here is the ScrollView docs reference which mentions the automaticallyAdjustContentInsets prop.
https://facebook.github.io/react-native/docs/scrollview.html#automaticallyadjustcontentinsets

Is this a bug caused by RNTableView or is this a misunderstanding on my end?

**Comment by sjchmiela** [comment]
Generally in native-native iOS putting UITableView inside UIScrollView isn't a good idea. http://stackoverflow.com/a/21857041/1123156

TableView component should react (😆 you get it – REACT) to its undocumented inset props https://github.com/aksonov/react-native-tableview/blob/master/index.js#L33, which somehow it ignores (at least it seems like doing it).

**Comment by sjchmiela** [comment]
Adding `[self.tableView setContentInset:_contentInset];` to `layoutSubviews` of `RNTableView` seems to fix the problem. Probably ViewController overwrites insets…

**Comment by sjchmiela** [comment]
Mea culpa – TableView reacts to inset props. But you cannot have the TableView positioned absolutely at `{0, 0, 0, 0}`. I removed it and left only `flex: 1` and it started to work!

**Comment by nickw444** [comment]
Did this end up being resolved? I also seem to be having an issue where the edge insets aren't being set correctly

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
