### ISSUE TITLE
How to customize Section header?

### ISSUE THREAD

**Issue by ajoshdee** [aksonov/react-native-tableview#79]
I want to change the contents and style of the section header. How to do it?

**Comment by allanjsx** [comment]
+1 Would love to see if there's a way to modify the font and background color of section header.

**Comment by allanjsx** [comment]
I don't see a way to change background color yet, but you can change the section header font color/ font family/ font size, such as:

    <TableView
          style={{flex:1, backgroundColor: "white"}}
          headerFontFamily={MyStyle.fontFamily}
          headerFontWeight={MyStyle.fontWeight}
          headerFontSize={16}
          separatorColor={MyStyle.color}>

Please look at RNTableViewManager.m for detail

**Comment by nickw** [comment]
@ajoshdee feel free to re-open if you are looking to customize more than font properties.

**Comment by ajoshdee** [comment]
I want to add buttons to header/footer
