### ISSUE TITLE
Some problems found

### ISSUE THREAD

**Issue by leecmm** [aksonov/react-native-tableview#89]
**UITableView**    **commitEditingStyle**  Should be judged  **customCells**

**Comment by leecmm** [comment]
<img width="826" alt="695193fe-2e4a-4355-b798-4761039f3ead" src="https://cloud.githubusercontent.com/assets/5915703/14490147/b4db533a-01a3-11e6-91f0-540915cf5395.png">

**Comment by aksonov** [comment]
I don't understand, could you clarify?

**Comment by leecmm** [comment]
<img width="673" alt="4ee7c58b-fd03-4c3e-930d-2f8616e503b2" src="https://cloud.githubusercontent.com/assets/5915703/14599740/ac43e246-058b-11e6-8cdb-66a5661a8118.png">

<img width="789" alt="530a74f6-8af5-4b8b-bca1-347d5ab9b088" src="https://cloud.githubusercontent.com/assets/5915703/14599893/91d90606-058c-11e6-9ca4-9c0c739eb8b4.png">

**Comment by aksonov** [comment]
Sorry, explain it in normal English or i have to close this issue...

**Comment by leecmm** [comment]
Use custom cell delete will flash back

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
