### ISSUE TITLE
the TableView doesn't display

### ISSUE THREAD

**Issue by xuxiang32** [aksonov/react-native-tableview#96]
I tried wrapping the TableView View ,the TableView doesn't display at all in that case.
Is this a misunderstanding on my end?

**Comment by xuxiang32** [comment]
var MyCenter = React.createClass({
   render(){
       return(
           <View style={styles.marginTop25}>

               <TableView style={{flex:1}}
                          contentOffset={{y:260}}
                          allowsToggle={true}
                          allowsMultipleSelection={true}
                          tableViewStyle={TableView.Consts.Style.Grouped}
                          tableViewCellStyle={TableView.Consts.CellStyle.Subtitle}
                          onPress={(event)=>console.log(event)}  >
                   <Section label="Section 1" arrow={true}>
                       <Item value="1" detail="Detail">Item 1</Item>
                       <Item value="2" detail="Detail2">Item 2</Item>

                   </Section>

               </TableView>


           </View>
       )
   }
});

**Comment by xuxiang32** [comment]
```
var MyCenter = React.createClass({
   render(){
       return(
           <View style={styles.marginTop25}>

               <TableView style={{flex:1}}
                          contentOffset={{y:260}}
                          allowsToggle={true}
                          allowsMultipleSelection={true}
                          tableViewStyle={TableView.Consts.Style.Grouped}
                          tableViewCellStyle={TableView.Consts.CellStyle.Subtitle}
                          onPress={(event)=>console.log(event)}  >
                   <Section label="Section 1" arrow={true}>
                       <Item value="1" detail="Detail">Item 1</Item>
                       <Item value="2" detail="Detail2">Item 2</Item>

                   </Section>

               </TableView>


           </View>
       )
   }
});
```

**Comment by xuxiang32** [comment]
@aksonov Could you help me ?

**Comment by PaulBGD** [comment]
I'm having the same thing happen, is there no way to include other non-table views?

**Comment by CNDonny** [comment]
when you wrapper it with <View> tag,  you must specify the height of the view.
I solve the problem by this method.

**Comment by PaulBGD** [comment]
Add flex: 1 to the view.

**Comment by mithunm93** [comment]
@PaulBGD's solution worked for me
