### ISSUE TITLE
Cells does not display when use Header Footer 

### ISSUE THREAD

**Issue by dengcqw** [aksonov/react-native-tableview#97]
```
<TableView.Header>
       <Text>This is tableView header</Text>
</TableView.Header>

<Section label="Section 2" arrow={false}>
    <Cell style={{flexDirection:'column', backgroundColor:'red'}}>
        <Text style={{textAlign:'center',fontSize:18}}> React Native </Text>
    </Cell>
</Section>
```

cause TableView._stateFormProps() index error for the section
this section index should be 0, but 1 here 
eventually,  numberOfRowsInSection return zero cell

**Comment by aksonov** [comment]
@nyura123, @nickw could you check?

**Comment by nyura123** [comment]
@dengcqw yes, it's a problem with how section index is calculated in `RNTableView` for `Cell`'s. In general there are a few issues with `Cell`'s which don't happen with `Item`'s, so might be worth trying https://github.com/aksonov/react-native-tableview#editable-complex-components if you need custom cells.

**Comment by phaibin** [comment]
@dengcqw Simply put TableView.Header & TableView.Footer under all section tags will fix it.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
