### ISSUE TITLE
Enable null child of Section

### ISSUE THREAD

**Issue by sibelius** [aksonov/react-native-tableview#98]
I have some optional Cell that I only want to show them in some situations.

Is there a way to accept a null value inside of a Section component? or hide a Cell?

**Comment by aksonov** [comment]
@nyura123 could you check?

**Comment by nyura123** [comment]
@sibeliusseraphini could you try reactModuleForCell prop? It is supposed to be for situations when you want to dynamically change table cells. To hide a cell you would not include the Item in table's children. More info is in Editable Complex Components in Readme, and examples in TableViewDemo for ex. Custom Editable.

**Comment by iRoachie** [comment]
Hey new maintainer here. Closing out all* issues from before 2017. If this is still a concern, please create a new issue. Thanks
